services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # The name of our first service
  backend:
    # Tell Docker where to find the Dockerfile
    build: ./backend
    
    # Inside docker 8000 -> Outside docker 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    
    # The "Mirror" (Volumes)
    # This keeps local code and the container code in sync
    volumes:
      - ./backend:/app
volumes:
  mongo_data: